FROM golang:1.27.1-alpine AS builder
ENV DESIRED_VERSION=v4.2.2
ENV HELM_DIFF_VERSION=v3.15.10
WORKDIR /go/src/github.com/target/impeller
COPY . .
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=linux
RUN apk add --no-cache git && \
    go mod vendor && \
    go build -mod vendor -a -installsuffix cgo -ldflags '-extldflags "-static"' -o impeller . && \
    go test -v -coverprofile cp.out
RUN apk add --update openssl && \
    rm -rf /var/cache/apk/*
RUN apk update && apk add bash git openssh
RUN apk add ca-certificates curl gpg gpg-agent
RUN cd /tmp && \
    wget -O get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 \
    && chmod +x get_helm.sh \
    && ./get_helm.sh
RUN curl -sL https://github.com/databus23.gpg | gpg --import
RUN gpgconf --kill all
RUN rm ~/.gnupg/*.lock || echo "no locks found"
RUN rm -f ~/.gnupg/public-keys.d/pubring.db.lock || echo "pubring.db.lock not found"
RUN gpgconf --reload gpg-agent
RUN gpg --output ~/.gnupg/pubring.gpg --export
RUN helm plugin install https://github.com/databus23/helm-diff/releases/download/${HELM_DIFF_VERSION}/helm-diff-linux-amd64.tgz

FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine
RUN gcloud components install gke-gcloud-auth-plugin

ENV KUBECTL_VERSION=v1.34.1
RUN apk add ca-certificates
RUN wget -O /usr/bin/kubectl https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl && \
    chmod +x /usr/bin/kubectl
RUN mkdir /root/.kube
ENV USE_GKE_GCLOUD_AUTH_PLUGIN=True
ENTRYPOINT ["/usr/bin/impeller"]
COPY --from=builder /go/src/github.com/target/impeller/impeller /usr/bin/impeller
COPY --from=builder /usr/local/bin/helm /usr/local/bin/helm
COPY --from=builder /root/.local /root/.local
COPY --from=builder /root/.cache /root/.cache
